server:
    port: 8081

spring:
  datasource:
    password: Surya@555
    url: jdbc:mysql://localhost:3306/campaign?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # security:
  #   user:
  #     name: admin
  #     # password: admin123



eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}     

management:
  tracing:
    sampling:
      probability: 1.0
